### ISSUE TITLE
How do i set this on story board?

### ISSUE THREAD

**Issue by patchthecode** [qiuncheng/FontAwesomeKit.Swift#3]
Lets say I have a UILabel on the story board.
How do I set the font of this without using code?

It might be good to just include a sample project on your github. (i could not find one when I downloaded your project)

**Comment by status302** [comment]
@patchthecode So sorry, this kit doesn't support setting the icon on UILabel on Storyboard, but I will complete that soon.

**Comment by patchthecode** [comment]
damn. ah shame. 
ok cool. then i'll look around for another pod in the mean time. thanks.
