### ISSUE TITLE
Swift 4 issue.

### ISSUE THREAD

**Issue by saqibomer** [qiuncheng/FontAwesomeKit.Swift#6]
Xcode: 9.0 GM.
Swift  : 4.0

Following is the issue in 'FontAwesomeKit.swift' 
Line # 206. 
```

// Previous Code

if !CTFontManagerRegisterGraphicsFont(font, &error) {

// New Codeto fix.

if !CTFontManagerRegisterGraphicsFont(font!, &error) {
```

There are two warnings in 'FontAwesomeAble.swift'
Line # 76 and 80. 

> 'substring(from:)' is deprecated: Please use String slicing subscript with a 'partial range from' opera
Please fix these and update your repo.

**Comment by status302** [comment]
Hi, @saqibomer , you can try `pod update` now .
