### ISSUE TITLE
Getting Deprecation Warning

### ISSUE THREAD

**Issue by MohanRamanathan** [qiuncheng/FontAwesomeKit.Swift#7]
let str1 = String.fontAwesome(undefined: 0xf107) 

for the above line i am getting the below deprecation warning,
'fontAwesome(undefined:)' is deprecated: Deprecated now, use `fa.fontAwesome(undefined:)` instead.

if i change to fa.fontAwesome, i am getting "Instance member 'fa' cannot be used on type 'String' "

**Comment by status302** [comment]
Yeah, It's a bug indeed.

**Comment by status302** [comment]
Hi @MohanRamanathan , fixed in [0.4.3](https://github.com/qiuncheng/FontAwesomeKit.Swift/releases/tag/0.4.3),
you can try `pod update` now.
![image](https://user-images.githubusercontent.com/9990834/40315835-18b59b5a-5d4f-11e8-8979-044f91e1de73.png)
