### ISSUE TITLE
error in UIImage

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [qiuncheng/FontAwesomeKit.Swift#8]
when i used this line of code
`let image = UIImage(awesomeType: .github, size: 30.0, color: UIColor.black)`
this error appear
Argument labels '(awesomeType:, size:, color:)' do not match any available overloads

**Comment by status302** [comment]
Hi @BurierAbdalwahhabElia , Thanks for your feedback,
The 1.0.1 was released, and this bug will be fixed.
